/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IModule,
  IModuleInterface,
} from "../../../../../contracts/interfaces/modules/base/IModule";

const _abi = [
  {
    inputs: [],
    name: "name",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IModule__factory {
  static readonly abi = _abi;
  static createInterface(): IModuleInterface {
    return new Interface(_abi) as IModuleInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IModule {
    return new Contract(address, _abi, runner) as unknown as IModule;
  }
}
