/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface IArbitrationPolicyInterface extends Interface {
  getFunction(
    nameOrSignature: "onDisputeCancel" | "onDisputeJudgement" | "onRaiseDispute"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "onDisputeCancel",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onDisputeJudgement",
    values: [BigNumberish, boolean, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onRaiseDispute",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "onDisputeCancel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onDisputeJudgement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onRaiseDispute",
    data: BytesLike
  ): Result;
}

export interface IArbitrationPolicy extends BaseContract {
  connect(runner?: ContractRunner | null): IArbitrationPolicy;
  waitForDeployment(): Promise<this>;

  interface: IArbitrationPolicyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  onDisputeCancel: TypedContractMethod<
    [caller: AddressLike, disputeId: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;

  onDisputeJudgement: TypedContractMethod<
    [disputeId: BigNumberish, decision: boolean, data: BytesLike],
    [void],
    "nonpayable"
  >;

  onRaiseDispute: TypedContractMethod<
    [caller: AddressLike, data: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "onDisputeCancel"
  ): TypedContractMethod<
    [caller: AddressLike, disputeId: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "onDisputeJudgement"
  ): TypedContractMethod<
    [disputeId: BigNumberish, decision: boolean, data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "onRaiseDispute"
  ): TypedContractMethod<
    [caller: AddressLike, data: BytesLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
