/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as policies from "./policies";
export type { policies };
export type { DisputeModule } from "./DisputeModule";
