/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface ILiquidSplitFactoryInterface extends Interface {
  getFunction(nameOrSignature: "createLiquidSplitClone"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createLiquidSplitClone",
    values: [AddressLike[], BigNumberish[], BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createLiquidSplitClone",
    data: BytesLike
  ): Result;
}

export interface ILiquidSplitFactory extends BaseContract {
  connect(runner?: ContractRunner | null): ILiquidSplitFactory;
  waitForDeployment(): Promise<this>;

  interface: ILiquidSplitFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createLiquidSplitClone: TypedContractMethod<
    [
      accounts: AddressLike[],
      initAllocations: BigNumberish[],
      _distributorFee: BigNumberish,
      owner: AddressLike
    ],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createLiquidSplitClone"
  ): TypedContractMethod<
    [
      accounts: AddressLike[],
      initAllocations: BigNumberish[],
      _distributorFee: BigNumberish,
      owner: AddressLike
    ],
    [string],
    "nonpayable"
  >;

  filters: {};
}
