/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  AccessPermission,
  AccessPermissionInterface,
} from "../../../contracts/lib/AccessPermission";

const _abi = [
  {
    inputs: [],
    name: "ABSTAIN",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ALLOW",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "DENY",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x610112610053600b82828239805160001a607314610046577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060475760003560e01c80630b5dfc3914604c578063463ea0c1146066578063a1731a2b146080575b600080fd5b6052609a565b604051605d919060c3565b60405180910390f35b606c609f565b6040516077919060c3565b60405180910390f35b608660a4565b6040516091919060c3565b60405180910390f35b600181565b600281565b600081565b600060ff82169050919050565b60bd8160a9565b82525050565b600060208201905060d6600083018460b6565b9291505056fea2646970667358221220f23f0381a47d8bb2f602520dff67a9919dc81f5ef2e17b3b3e40c30556a0e22964736f6c63430008170033";

type AccessPermissionConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AccessPermissionConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AccessPermission__factory extends ContractFactory {
  constructor(...args: AccessPermissionConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      AccessPermission & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): AccessPermission__factory {
    return super.connect(runner) as AccessPermission__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AccessPermissionInterface {
    return new Interface(_abi) as AccessPermissionInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AccessPermission {
    return new Contract(address, _abi, runner) as unknown as AccessPermission;
  }
}
