/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as registries from "./registries";
export { AccessPermission__factory } from "./AccessPermission__factory";
export { Errors__factory } from "./Errors__factory";
