/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IAccessControllerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "checkPermission"
      | "getPermission"
      | "setGlobalPermission"
      | "setPermission"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "checkPermission",
    values: [AddressLike, AddressLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPermission",
    values: [AddressLike, AddressLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setGlobalPermission",
    values: [AddressLike, AddressLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPermission",
    values: [AddressLike, AddressLike, AddressLike, BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkPermission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPermission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGlobalPermission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPermission",
    data: BytesLike
  ): Result;
}

export interface IAccessController extends BaseContract {
  connect(runner?: ContractRunner | null): IAccessController;
  waitForDeployment(): Promise<this>;

  interface: IAccessControllerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkPermission: TypedContractMethod<
    [
      ipAccount_: AddressLike,
      signer_: AddressLike,
      to_: AddressLike,
      func_: BytesLike
    ],
    [boolean],
    "view"
  >;

  getPermission: TypedContractMethod<
    [
      ipAccount_: AddressLike,
      signer_: AddressLike,
      to_: AddressLike,
      func_: BytesLike
    ],
    [bigint],
    "view"
  >;

  setGlobalPermission: TypedContractMethod<
    [
      signer_: AddressLike,
      to_: AddressLike,
      func_: BytesLike,
      permission_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setPermission: TypedContractMethod<
    [
      ipAccount_: AddressLike,
      signer_: AddressLike,
      to_: AddressLike,
      func_: BytesLike,
      permission_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkPermission"
  ): TypedContractMethod<
    [
      ipAccount_: AddressLike,
      signer_: AddressLike,
      to_: AddressLike,
      func_: BytesLike
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPermission"
  ): TypedContractMethod<
    [
      ipAccount_: AddressLike,
      signer_: AddressLike,
      to_: AddressLike,
      func_: BytesLike
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "setGlobalPermission"
  ): TypedContractMethod<
    [
      signer_: AddressLike,
      to_: AddressLike,
      func_: BytesLike,
      permission_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPermission"
  ): TypedContractMethod<
    [
      ipAccount_: AddressLike,
      signer_: AddressLike,
      to_: AddressLike,
      func_: BytesLike,
      permission_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
