/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as licensing from "./licensing";
export type { licensing };
import type * as modules from "./modules";
export type { modules };
import type * as registries from "./registries";
export type { registries };
import type * as resolvers from "./resolvers";
export type { resolvers };
export type { IAccessController } from "./IAccessController";
export type { IIPAccount } from "./IIPAccount";
