/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPMetadataResolver__factory } from "./IPMetadataResolver__factory";
export { ResolverBase__factory } from "./ResolverBase__factory";
