blank_issues_enabled: false
contact_links:
  - name: Story Protocol Official Discord
    url: https://discord.gg/storyprotocol
    about: If you're a user, this is the fastest way to get help. Do not give your wallet private key or mnemonic words to anyone.
