/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPAccountRegistry } from "./IPAccountRegistry";
export type { IPRecordRegistry } from "./IPRecordRegistry";
export type { LicenseRegistry } from "./LicenseRegistry";
export type { ModuleRegistry } from "./ModuleRegistry";
