/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IPAccountRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ACCESS_CONTROLLER"
      | "ERC6551_PUBLIC_REGISTRY"
      | "IP_ACCOUNT_IMPL"
      | "IP_ACCOUNT_SALT"
      | "getIPAccountImpl"
      | "ipAccount"
      | "registerIpAccount"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "IPAccountRegistered"): EventFragment;

  encodeFunctionData(
    functionFragment: "ACCESS_CONTROLLER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ERC6551_PUBLIC_REGISTRY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "IP_ACCOUNT_IMPL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "IP_ACCOUNT_SALT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getIPAccountImpl",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ipAccount",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerIpAccount",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "ACCESS_CONTROLLER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ERC6551_PUBLIC_REGISTRY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "IP_ACCOUNT_IMPL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "IP_ACCOUNT_SALT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIPAccountImpl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ipAccount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerIpAccount",
    data: BytesLike
  ): Result;
}

export namespace IPAccountRegisteredEvent {
  export type InputTuple = [
    account: AddressLike,
    implementation: AddressLike,
    chainId: BigNumberish,
    tokenContract: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [
    account: string,
    implementation: string,
    chainId: bigint,
    tokenContract: string,
    tokenId: bigint
  ];
  export interface OutputObject {
    account: string;
    implementation: string;
    chainId: bigint;
    tokenContract: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPAccountRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IPAccountRegistry;
  waitForDeployment(): Promise<this>;

  interface: IPAccountRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ACCESS_CONTROLLER: TypedContractMethod<[], [string], "view">;

  ERC6551_PUBLIC_REGISTRY: TypedContractMethod<[], [string], "view">;

  IP_ACCOUNT_IMPL: TypedContractMethod<[], [string], "view">;

  IP_ACCOUNT_SALT: TypedContractMethod<[], [string], "view">;

  getIPAccountImpl: TypedContractMethod<[], [string], "view">;

  ipAccount: TypedContractMethod<
    [
      chainId_: BigNumberish,
      tokenContract_: AddressLike,
      tokenId_: BigNumberish
    ],
    [string],
    "view"
  >;

  registerIpAccount: TypedContractMethod<
    [
      chainId_: BigNumberish,
      tokenContract_: AddressLike,
      tokenId_: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ACCESS_CONTROLLER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ERC6551_PUBLIC_REGISTRY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "IP_ACCOUNT_IMPL"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "IP_ACCOUNT_SALT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getIPAccountImpl"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ipAccount"
  ): TypedContractMethod<
    [
      chainId_: BigNumberish,
      tokenContract_: AddressLike,
      tokenId_: BigNumberish
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerIpAccount"
  ): TypedContractMethod<
    [
      chainId_: BigNumberish,
      tokenContract_: AddressLike,
      tokenId_: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  getEvent(
    key: "IPAccountRegistered"
  ): TypedContractEvent<
    IPAccountRegisteredEvent.InputTuple,
    IPAccountRegisteredEvent.OutputTuple,
    IPAccountRegisteredEvent.OutputObject
  >;

  filters: {
    "IPAccountRegistered(address,address,uint256,address,uint256)": TypedContractEvent<
      IPAccountRegisteredEvent.InputTuple,
      IPAccountRegisteredEvent.OutputTuple,
      IPAccountRegisteredEvent.OutputObject
    >;
    IPAccountRegistered: TypedContractEvent<
      IPAccountRegisteredEvent.InputTuple,
      IPAccountRegisteredEvent.OutputTuple,
      IPAccountRegisteredEvent.OutputObject
    >;
  };
}
