/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IIPAccountRegistry__factory } from "./IIPAccountRegistry__factory";
export { IIPRecordRegistry__factory } from "./IIPRecordRegistry__factory";
export { IModuleRegistry__factory } from "./IModuleRegistry__factory";
