/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as disputeModule from "./dispute-module";
export type { disputeModule };
import type * as royaltyModule from "./royalty-module";
export type { royaltyModule };
