/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPAccountRegistry__factory } from "./IPAccountRegistry__factory";
export { IPRecordRegistry__factory } from "./IPRecordRegistry__factory";
export { LicenseRegistry__factory } from "./LicenseRegistry__factory";
export { ModuleRegistry__factory } from "./ModuleRegistry__factory";
