/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPMetadataResolver } from "./IPMetadataResolver";
export type { ResolverBase } from "./ResolverBase";
