/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IIPAccountRegistry } from "./IIPAccountRegistry";
export type { IIPRecordRegistry } from "./IIPRecordRegistry";
export type { IModuleRegistry } from "./IModuleRegistry";
