/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface RoyaltyPolicyLSInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "LIQUID_SPLIT_FACTORY"
      | "LIQUID_SPLIT_MAIN"
      | "ROYALTY_MODULE"
      | "claimRoyalties"
      | "distributeFunds"
      | "initPolicy"
      | "onRoyaltyPayment"
      | "splitClones"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "LIQUID_SPLIT_FACTORY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LIQUID_SPLIT_MAIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ROYALTY_MODULE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimRoyalties",
    values: [AddressLike, BigNumberish, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeFunds",
    values: [AddressLike, AddressLike, AddressLike[], AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initPolicy",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onRoyaltyPayment",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "splitClones",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "LIQUID_SPLIT_FACTORY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LIQUID_SPLIT_MAIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ROYALTY_MODULE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRoyalties",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initPolicy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onRoyaltyPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "splitClones",
    data: BytesLike
  ): Result;
}

export interface RoyaltyPolicyLS extends BaseContract {
  connect(runner?: ContractRunner | null): RoyaltyPolicyLS;
  waitForDeployment(): Promise<this>;

  interface: RoyaltyPolicyLSInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  LIQUID_SPLIT_FACTORY: TypedContractMethod<[], [string], "view">;

  LIQUID_SPLIT_MAIN: TypedContractMethod<[], [string], "view">;

  ROYALTY_MODULE: TypedContractMethod<[], [string], "view">;

  claimRoyalties: TypedContractMethod<
    [_account: AddressLike, _withdrawETH: BigNumberish, _tokens: AddressLike[]],
    [void],
    "nonpayable"
  >;

  distributeFunds: TypedContractMethod<
    [
      _ipId: AddressLike,
      _token: AddressLike,
      _accounts: AddressLike[],
      _distributorAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  initPolicy: TypedContractMethod<
    [_ipId: AddressLike, _data: BytesLike],
    [void],
    "nonpayable"
  >;

  onRoyaltyPayment: TypedContractMethod<
    [
      _caller: AddressLike,
      _ipId: AddressLike,
      _token: AddressLike,
      _amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  splitClones: TypedContractMethod<[ipId: AddressLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "LIQUID_SPLIT_FACTORY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LIQUID_SPLIT_MAIN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ROYALTY_MODULE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claimRoyalties"
  ): TypedContractMethod<
    [_account: AddressLike, _withdrawETH: BigNumberish, _tokens: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "distributeFunds"
  ): TypedContractMethod<
    [
      _ipId: AddressLike,
      _token: AddressLike,
      _accounts: AddressLike[],
      _distributorAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initPolicy"
  ): TypedContractMethod<
    [_ipId: AddressLike, _data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "onRoyaltyPayment"
  ): TypedContractMethod<
    [
      _caller: AddressLike,
      _ipId: AddressLike,
      _token: AddressLike,
      _amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "splitClones"
  ): TypedContractMethod<[ipId: AddressLike], [string], "view">;

  filters: {};
}
