/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILiquidSplitMain,
  ILiquidSplitMainInterface,
} from "../../../../../interfaces/modules/royalty-module/policies/ILiquidSplitMain";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "withdrawETH",
        type: "uint256",
      },
      {
        internalType: "contract ERC20[]",
        name: "tokens",
        type: "address[]",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ILiquidSplitMain__factory {
  static readonly abi = _abi;
  static createInterface(): ILiquidSplitMainInterface {
    return new Interface(_abi) as ILiquidSplitMainInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ILiquidSplitMain {
    return new Contract(address, _abi, runner) as unknown as ILiquidSplitMain;
  }
}
