/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILiquidSplitClone,
  ILiquidSplitCloneInterface,
} from "../../../../../interfaces/modules/royalty-module/policies/ILiquidSplitClone";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address[]",
        name: "accounts",
        type: "address[]",
      },
      {
        internalType: "address",
        name: "distributorAddress",
        type: "address",
      },
    ],
    name: "distributeFunds",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ILiquidSplitClone__factory {
  static readonly abi = _abi;
  static createInterface(): ILiquidSplitCloneInterface {
    return new Interface(_abi) as ILiquidSplitCloneInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ILiquidSplitClone {
    return new Contract(address, _abi, runner) as unknown as ILiquidSplitClone;
  }
}
