/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRoyaltyPolicy,
  IRoyaltyPolicyInterface,
} from "../../../../../interfaces/modules/royalty-module/policies/IRoyaltyPolicy";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "ipId",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "initPolicy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        internalType: "address",
        name: "ipId",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "onRoyaltyPayment",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRoyaltyPolicy__factory {
  static readonly abi = _abi;
  static createInterface(): IRoyaltyPolicyInterface {
    return new Interface(_abi) as IRoyaltyPolicyInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRoyaltyPolicy {
    return new Contract(address, _abi, runner) as unknown as IRoyaltyPolicy;
  }
}
