/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IParamVerifierInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "json"
      | "verifyActivationParam"
      | "verifyLinkParentParam"
      | "verifyMintingParam"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "json", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifyActivationParam",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyLinkParentParam",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyMintingParam",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "json", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyActivationParam",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyLinkParentParam",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyMintingParam",
    data: BytesLike
  ): Result;
}

export interface IParamVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): IParamVerifier;
  waitForDeployment(): Promise<this>;

  interface: IParamVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  json: TypedContractMethod<[], [string], "view">;

  verifyActivationParam: TypedContractMethod<
    [caller: AddressLike, data: BytesLike],
    [boolean],
    "nonpayable"
  >;

  verifyLinkParentParam: TypedContractMethod<
    [caller: AddressLike, data: BytesLike],
    [boolean],
    "nonpayable"
  >;

  verifyMintingParam: TypedContractMethod<
    [caller: AddressLike, mintAmount: BigNumberish, data: BytesLike],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "json"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifyActivationParam"
  ): TypedContractMethod<
    [caller: AddressLike, data: BytesLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyLinkParentParam"
  ): TypedContractMethod<
    [caller: AddressLike, data: BytesLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyMintingParam"
  ): TypedContractMethod<
    [caller: AddressLike, mintAmount: BigNumberish, data: BytesLike],
    [boolean],
    "nonpayable"
  >;

  filters: {};
}
