/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface AccessPermissionInterface extends Interface {
  getFunction(nameOrSignature: "ABSTAIN" | "ALLOW" | "DENY"): FunctionFragment;

  encodeFunctionData(functionFragment: "ABSTAIN", values?: undefined): string;
  encodeFunctionData(functionFragment: "ALLOW", values?: undefined): string;
  encodeFunctionData(functionFragment: "DENY", values?: undefined): string;

  decodeFunctionResult(functionFragment: "ABSTAIN", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ALLOW", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "DENY", data: BytesLike): Result;
}

export interface AccessPermission extends BaseContract {
  connect(runner?: ContractRunner | null): AccessPermission;
  waitForDeployment(): Promise<this>;

  interface: AccessPermissionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ABSTAIN: TypedContractMethod<[], [bigint], "view">;

  ALLOW: TypedContractMethod<[], [bigint], "view">;

  DENY: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ABSTAIN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ALLOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DENY"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
