/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as registries from "./registries";
export type { registries };
export type { AccessPermission } from "./AccessPermission";
export type { Errors } from "./Errors";
