/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IIPMetadataResolver } from "./IIPMetadataResolver";
export type { IResolver } from "./IResolver";
